# Generated by Django 2.2.3 on 2022-01-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_customer_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_signup',
            name='gender',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
